name: testing workflow
on: workflow_dispatch
jobs:
  testactions:
    runs-on: ubuntu-latest
    steps:
       - name: test action
         uses: actions/checkout@v3
       - name: list downloaded directory
         run: |
            echo $GITHUB_WORKSPACE
            ls -ltr $GITHUB_WORKSPACE
              
